<?php
require dirname(__DIR__) . '/src/bootstrap.php';
$user=require_admin();
$id=(int)($_GET['id']??0);
$stmt=$pdo->prepare('SELECT i.*,c.nombre categoria,e.nombre evento,e.cupos,p.id pago_id,p.estado pago_estado,p.yappy_numero,p.nombre_titular,p.referencia,p.fecha_pago,p.monto,p.nombre_original,p.mime_type,p.observaciones,p.fecha_validacion,u.nombre validador FROM inscripciones i JOIN categorias c ON c.id=i.categoria_id JOIN eventos e ON e.id=i.evento_id JOIN pagos p ON p.inscripcion_id=i.id LEFT JOIN usuarios u ON u.id=p.validado_por WHERE i.id=?');$stmt->execute([$id]);$r=$stmt->fetch();if(!$r){http_response_code(404);exit('Inscripción no encontrada.');}
$pageTitle='Inscripción '.$r['codigo'];require __DIR__.'/_header.php';
?>
<div class="admin-heading"><div><span class="section-kicker">Detalle de inscripción</span><h1><?=e($r['codigo'])?></h1><span class="badge <?=e(badge_class($r['estado']))?>"><?=e(payment_status_label($r['estado']))?></span></div><a class="btn btn-outline" href="inscripciones.php">Volver</a></div>
<section class="admin-grid detail-grid"><div class="card"><h2>Participante</h2><dl class="summary"><div><dt>Nombre</dt><dd><?=e(trim($r['primer_nombre'].' '.$r['segundo_nombre'].' '.$r['primer_apellido'].' '.$r['segundo_apellido']))?></dd></div><div><dt>Identificación</dt><dd><?=e($r['identificacion'])?></dd></div><div><dt>Nacimiento</dt><dd><?=e(date('d/m/Y',strtotime($r['fecha_nacimiento'])))?> (<?=$r['edad_evento']?> años)</dd></div><div><dt>Categoría</dt><dd><?=e($r['categoria'])?></dd></div><div><dt>Teléfono</dt><dd><?=e($r['telefono'])?></dd></div><div><dt>Correo</dt><dd><?=e($r['correo'])?></dd></div><div><dt>Emergencia</dt><dd><?=e($r['contacto_emergencia'].' · '.$r['telefono_emergencia'])?></dd></div><div><dt>Talla</dt><dd><?=e($r['talla_camiseta'])?></dd></div></dl></div>
<div class="card"><h2>Pago Yappy</h2><dl class="summary"><div><dt>Número receptor</dt><dd><?=e($r['yappy_numero'])?></dd></div><div><dt>Titular</dt><dd><?=e($r['nombre_titular'])?></dd></div><div><dt>Referencia</dt><dd><?=e($r['referencia']??'No indicada')?></dd></div><div><dt>Fecha</dt><dd><?=e(date('d/m/Y',strtotime($r['fecha_pago'])))?></dd></div><div><dt>Monto</dt><dd><?=e(format_money($r['monto']))?></dd></div><div><dt>Comprobante</dt><dd><a target="_blank" href="<?=e(url('comprobante.php?id='.$r['pago_id']))?>">Abrir archivo</a></dd></div><?php if($r['validador']):?><div><dt>Validado por</dt><dd><?=e($r['validador'])?> · <?=e(date('d/m/Y H:i',strtotime($r['fecha_validacion'])))?></dd></div><?php endif;?></dl><?php if($r['observaciones']):?><div class="alert alert-warning"><?=e($r['observaciones'])?></div><?php endif;?></div></section>
<?php if($r['estado']==='pago_pendiente'):?><section class="card action-card"><h2>Validar el pago</h2><p>Confirme en Yappy que el pago fue recibido al número <strong><?=e($r['yappy_numero'])?></strong>. Al confirmar, este registro ocupará un cupo.</p><div class="action-row"><form method="post" action="pago.php"><?=csrf_field()?><input type="hidden" name="id" value="<?=$r['id']?>"><input type="hidden" name="accion" value="confirmar"><button class="btn" type="submit">Confirmar pago y reservar cupo</button></form><form method="post" action="pago.php" class="reject-form"><?=csrf_field()?><input type="hidden" name="id" value="<?=$r['id']?>"><input type="hidden" name="accion" value="rechazar"><input name="observaciones" placeholder="Motivo del rechazo" required><button class="btn btn-danger" type="submit">Rechazar</button></form></div></section><?php elseif($r['estado']==='pago_confirmado'):?><section class="card action-card"><h2>Entrega de kit</h2><form method="post" action="kit.php" class="action-row"><?=csrf_field()?><input type="hidden" name="id" value="<?=$r['id']?>"><label>Talla entregada<select name="talla"><option><?=e($r['talla_camiseta'])?></option><?php foreach(['XS','S','M','L','XL','2XL','3XL'] as $s):if($s!==$r['talla_camiseta']):?><option><?=$s?></option><?php endif;endforeach;?></select></label><label>Observación<input name="observaciones"></label><button class="btn" type="submit">Marcar kit entregado</button></form></section><?php endif;?>
<?php require __DIR__.'/_footer.php'; ?>
